name: Deploy

on:
  push:
    branches:
      - main

concurrency: deploy-main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Build app bundle
        run: |
          cd frontend
          yarn install --frozen-lockfile
          echo REACT_APP_MORALIS_APP_ID=${{ secrets.REACT_APP_MORALIS_APP_ID }} >> .env
          echo REACT_APP_MORALIS_SERVER_URL=${{ secrets.REACT_APP_MORALIS_SERVER_URL }} >> .env
          echo REACT_APP_ALLOWED_NETWORK=${{ secrets.REACT_APP_ALLOWED_NETWORK }} >> .env
          echo REACT_APP_FACTORY_CONTRACT_ADDRESS=${{ secrets.REACT_APP_FACTORY_CONTRACT_ADDRESS }} >> .env
          echo REACT_APP_WEB3_STORAGE_TOKEN=${{ secrets.REACT_APP_WEB3_STORAGE_TOKEN }} >> .env
          export NODE_OPTIONS="--max-old-space-size=4096"
          CI= yarn build
      - name: Build CDK app stack
        run: |
          cd infra
          yarn install
          yarn build
      - name: Deploy App
        run: |
          cd infra
          export AWS_ACCOUNT_ID="${{ secrets.AWS_ACCOUNT_ID }}"
          export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
          export AWS_DEFAULT_REGION="${{ secrets.AWS_DEFAULT_REGION }}"
          export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          node_modules/.bin/cdk deploy --require-approval never --ci
